// Auto-generated by analysis/analyze-songs.ts — do not edit by hand.
// Re-run: npx tsx analysis/analyze-songs.ts
import type { EdgeType, IntervalStep } from './chordPathfinder';

export interface CyclePreset {
  loop: string;         // edge-type sequence, e.g. "fifth dom7"
  steps: IntervalStep[]; // interval shape derived from exampleChords
  length: number;       // number of steps (= edges in the loop)
  songCount: number;    // songs in the library containing this cycle
  constraints: EdgeType[];  // Walk constraints needed to traverse it
  exampleChords: string;   // concrete chord instance, e.g. "D A D"
  topSongs: Array<{ title: string; chords: string }>;
}

export const CYCLE_PRESETS: CyclePreset[] = [
  {
    "loop": "dom7 fifth",
    "steps": [{"semitones":5,"quality":"same"},{"semitones":7,"quality":"same"}],
    "length": 2,
    "songCount": 1732,
    "constraints": [
      "fifth",
      "dom7"
    ],
    "exampleChords": "E A E",
    "topSongs": [
      {
        "title": "nirvana - come as you are",
        "chords": "Am Dm Am"
      },
      {
        "title": "foo fighters - everlong",
        "chords": "A D A"
      },
      {
        "title": "police - every breath you take",
        "chords": "G C G"
      },
      {
        "title": "jackson michael - beat it",
        "chords": "C# F# C#"
      },
      {
        "title": "green day - basket case",
        "chords": "D# G# D#"
      },
      {
        "title": "ABBA - dancing queen",
        "chords": "E A E"
      },
      {
        "title": "radiohead - high and dry",
        "chords": "B E B"
      },
      {
        "title": "Cranberries - Linger",
        "chords": "A D A"
      }
    ]
  },
  {
    "loop": "diatonic diatonic",
    "steps": [{"semitones":10,"quality":"major"},{"semitones":2,"quality":"minor"}],
    "length": 2,
    "songCount": 1714,
    "constraints": [
      "diatonic"
    ],
    "exampleChords": "Bm A Bm",
    "topSongs": [
      {
        "title": "radiohead - karma police",
        "chords": "Bm Am Bm"
      },
      {
        "title": "foo fighters - everlong",
        "chords": "D E D"
      },
      {
        "title": "police - every breath you take",
        "chords": "D# F D#"
      },
      {
        "title": "a-ha - take on me",
        "chords": "D C#m D"
      },
      {
        "title": "red hot chilli peppers - under the bridge",
        "chords": "C#m B C#m"
      },
      {
        "title": "jackson michael - beat it",
        "chords": "C# B C#"
      },
      {
        "title": "green day - basket case",
        "chords": "G# A# G#"
      },
      {
        "title": "ABBA - dancing queen",
        "chords": "F#m E F#m"
      }
    ]
  },
  {
    "loop": "relative relative",
    "steps": [{"semitones":3,"quality":"major"},{"semitones":9,"quality":"minor"}],
    "length": 2,
    "songCount": 883,
    "constraints": [
      "relative"
    ],
    "exampleChords": "Fm G# Fm",
    "topSongs": [
      {
        "title": "foo fighters - everlong",
        "chords": "D Bm D"
      },
      {
        "title": "red hot chilli peppers - under the bridge",
        "chords": "F#m A F#m"
      },
      {
        "title": "green day - basket case",
        "chords": "D# Cm D#"
      },
      {
        "title": "Cranberries - Zombie",
        "chords": "Em G Em"
      },
      {
        "title": "radiohead - fake plastic trees",
        "chords": "A F#m A"
      },
      {
        "title": "soundgarden - black hole sun",
        "chords": "Fm G# Fm"
      },
      {
        "title": "weezer - buddy holly",
        "chords": "F#m A F#m"
      },
      {
        "title": "nirvana - dumb",
        "chords": "Em G Em"
      }
    ]
  },
  {
    "loop": "diatonic diatonic diatonic diatonic",
    "steps": [{"semitones":2,"quality":"same"},{"semitones":10,"quality":"same"},{"semitones":2,"quality":"same"},{"semitones":10,"quality":"same"}],
    "length": 4,
    "songCount": 745,
    "constraints": [
      "diatonic"
    ],
    "exampleChords": "C D C D C",
    "topSongs": [
      {
        "title": "police - every breath you take",
        "chords": "D# F D# F D#"
      },
      {
        "title": "red hot chilli peppers - under the bridge",
        "chords": "C#m B C#m B C#m"
      },
      {
        "title": "jackson michael - beat it",
        "chords": "C# B C# B C#"
      },
      {
        "title": "radiohead - high and dry",
        "chords": "E F#m E F#m E"
      },
      {
        "title": "toto - africa",
        "chords": "G#m A G#m A G#m"
      },
      {
        "title": "AC DC - highway to hell",
        "chords": "A G A G A"
      },
      {
        "title": "aerosmith - dream on",
        "chords": "D# C# D# C# D#"
      },
      {
        "title": "Bon Jovi - you give love a bad name",
        "chords": "G# A# G# A# G#"
      }
    ]
  },
  {
    "loop": "dom7 fifth dom7 fifth",
    "steps": [{"semitones":5,"quality":"same"},{"semitones":7,"quality":"same"},{"semitones":5,"quality":"same"},{"semitones":7,"quality":"same"}],
    "length": 4,
    "songCount": 676,
    "constraints": [
      "fifth",
      "dom7"
    ],
    "exampleChords": "E A E A E",
    "topSongs": [
      {
        "title": "green day - basket case",
        "chords": "D# G# D# G# D#"
      },
      {
        "title": "ABBA - dancing queen",
        "chords": "E A E A E"
      },
      {
        "title": "nirvana - all apologies",
        "chords": "C# F# C# F# C#"
      },
      {
        "title": "nirvana - rape me",
        "chords": "Em Am Em Am Em"
      },
      {
        "title": "foo fighters - my hero",
        "chords": "B E B E B"
      },
      {
        "title": "Boston - more than a feeling",
        "chords": "D G D G D"
      },
      {
        "title": "radiohead - subterranean homesick alien",
        "chords": "G C G C G"
      },
      {
        "title": "joel billy - piano man",
        "chords": "C F C F C"
      }
    ]
  },
  {
    "loop": "diatonic dom7 dom7",
    "steps": [{"semitones":2,"quality":"same"},{"semitones":5,"quality":"same"},{"semitones":5,"quality":"same"}],
    "length": 3,
    "songCount": 664,
    "constraints": [
      "diatonic",
      "dom7"
    ],
    "exampleChords": "G# A# D# G#",
    "topSongs": [
      {
        "title": "weezer - buddy holly",
        "chords": "G A D G"
      },
      {
        "title": "pink floyd - the great gig in the sky",
        "chords": "D# F A# D#"
      },
      {
        "title": "foo fighters - my hero",
        "chords": "E F#m B E"
      },
      {
        "title": "sublime - santeria",
        "chords": "A B E A"
      },
      {
        "title": "green day - when i come around",
        "chords": "B C# F# B"
      },
      {
        "title": "joel billy - uptown girl",
        "chords": "G Am Dm G"
      },
      {
        "title": "Billy Joel - Uptown Girl",
        "chords": "G Am Dm G"
      },
      {
        "title": "Cyndi Lauper - Girls Just Want to Have Fun",
        "chords": "B C# F# B"
      }
    ]
  },
  {
    "loop": "diatonic fifth fifth",
    "steps": [{"semitones":10,"quality":"same"},{"semitones":7,"quality":"same"},{"semitones":7,"quality":"same"}],
    "length": 3,
    "songCount": 432,
    "constraints": [
      "fifth",
      "diatonic"
    ],
    "exampleChords": "D C G D",
    "topSongs": [
      {
        "title": "red hot chilli peppers - under the bridge",
        "chords": "B A E B"
      },
      {
        "title": "Queen - bohemian rhapsody",
        "chords": "A# G# D# A#"
      },
      {
        "title": "Queen - Queen Bohemian Rhapsody",
        "chords": "A# G# D# A#"
      },
      {
        "title": "CCR - Fortunate Son",
        "chords": "G F C G"
      },
      {
        "title": "Bon Jovi - you give love a bad name",
        "chords": "F D# A# F"
      },
      {
        "title": "Boston - more than a feeling",
        "chords": "D C G D"
      },
      {
        "title": "Cyndi Lauper - Girls Just Want to Have Fun",
        "chords": "C# B F# C#"
      },
      {
        "title": "Rollin STones - Gimme Shelter",
        "chords": "B A E B"
      }
    ]
  },
  {
    "loop": "diatonic diatonic dom7 fifth",
    "steps": [{"semitones":10,"quality":"same"},{"semitones":2,"quality":"same"},{"semitones":5,"quality":"same"},{"semitones":7,"quality":"same"}],
    "length": 4,
    "songCount": 377,
    "constraints": [
      "fifth",
      "diatonic",
      "dom7"
    ],
    "exampleChords": "E D E A E",
    "topSongs": [
      {
        "title": "jackson michael - beat it",
        "chords": "C# B C# F# C#"
      },
      {
        "title": "ABBA - dancing queen",
        "chords": "E F#m E A E"
      },
      {
        "title": "earth wind fire - september",
        "chords": "E F#m E A E"
      },
      {
        "title": "Boston - more than a feeling",
        "chords": "D C D G D"
      },
      {
        "title": "Cyndi Lauper - Girls Just Want to Have Fun",
        "chords": "C# B C# F# C#"
      },
      {
        "title": "joel billy - piano man",
        "chords": "C Dm C F C"
      },
      {
        "title": "Billy Joel - Piano Man",
        "chords": "C Dm C F C"
      },
      {
        "title": "van morrison - brown eyed girl",
        "chords": "D C D G D"
      }
    ]
  },
  {
    "loop": "diatonic diatonic fifth dom7",
    "steps": [{"semitones":2,"quality":"minor"},{"semitones":10,"quality":"major"},{"semitones":7,"quality":"same"},{"semitones":5,"quality":"same"}],
    "length": 4,
    "songCount": 356,
    "constraints": [
      "fifth",
      "diatonic",
      "dom7"
    ],
    "exampleChords": "F Gm F C F",
    "topSongs": [
      {
        "title": "green day - basket case",
        "chords": "G# A# G# D# G#"
      },
      {
        "title": "radiohead - high and dry",
        "chords": "E F#m E B E"
      },
      {
        "title": "Cranberries - Linger",
        "chords": "C D C G C"
      },
      {
        "title": "spice girls - wannabe",
        "chords": "E F# E B E"
      },
      {
        "title": "oasis - don't look back in anger",
        "chords": "F G F C F"
      },
      {
        "title": "Cyndi Lauper - Time after Time",
        "chords": "F Em F C F"
      },
      {
        "title": "green day - brain stew",
        "chords": "G A G D G"
      },
      {
        "title": "prince - purple rain",
        "chords": "D E D A D"
      }
    ]
  },
  {
    "loop": "borrowed borrowed",
    "steps": [{"semitones":9,"quality":"same"},{"semitones":3,"quality":"same"}],
    "length": 2,
    "songCount": 348,
    "constraints": [
      "borrowed"
    ],
    "exampleChords": "G# F G#",
    "topSongs": [
      {
        "title": "jackson michael - billie jean",
        "chords": "B D B"
      },
      {
        "title": "ABBA - dancing queen",
        "chords": "E C# E"
      },
      {
        "title": "nirvana - heart shaped box",
        "chords": "F D F"
      },
      {
        "title": "weezer - buddy holly",
        "chords": "D F# D"
      },
      {
        "title": "nirvana - dumb",
        "chords": "A C A"
      },
      {
        "title": "nirvana - in bloom",
        "chords": "D A# D"
      },
      {
        "title": "nirvana - rape me",
        "chords": "A C A"
      },
      {
        "title": "dire straits - sultans of swing",
        "chords": "C A C"
      }
    ]
  },
  {
    "loop": "diatonic dom7 relative",
    "steps": [{"semitones":10,"quality":"major"},{"semitones":5,"quality":"same"},{"semitones":9,"quality":"minor"}],
    "length": 3,
    "songCount": 324,
    "constraints": [
      "diatonic",
      "relative",
      "dom7"
    ],
    "exampleChords": "Fm D# G# Fm",
    "topSongs": [
      {
        "title": "jackson michael - billie jean",
        "chords": "C#m B E C#m"
      },
      {
        "title": "radiohead - karma police",
        "chords": "Bm Am D Bm"
      },
      {
        "title": "police - every breath you take",
        "chords": "Em D G Em"
      },
      {
        "title": "red hot chilli peppers - under the bridge",
        "chords": "C#m B E C#m"
      },
      {
        "title": "ABBA - dancing queen",
        "chords": "F#m E A F#m"
      },
      {
        "title": "radiohead - fake plastic trees",
        "chords": "Bm A D Bm"
      },
      {
        "title": "REM - Losing My Religion",
        "chords": "Em Dm G Em"
      },
      {
        "title": "nirvana - dumb",
        "chords": "Em D G Em"
      }
    ]
  },
  {
    "loop": "parallel parallel",
    "steps": [{"semitones":0,"quality":"major"},{"semitones":0,"quality":"minor"}],
    "length": 2,
    "songCount": 274,
    "constraints": [
      "parallel"
    ],
    "exampleChords": "Bm B Bm",
    "topSongs": [
      {
        "title": "nirvana - lithium",
        "chords": "Am A Am"
      },
      {
        "title": "jackson michael - beat it",
        "chords": "D#m D# D#m"
      },
      {
        "title": "nirvana - dumb",
        "chords": "Em E Em"
      },
      {
        "title": "rage against the machine - killing in the name of",
        "chords": "Dm D Dm"
      },
      {
        "title": "earth wind fire - september",
        "chords": "C#m C# C#m"
      },
      {
        "title": "pearl jam - even flow",
        "chords": "Dm D Dm"
      },
      {
        "title": "weezer - say it ain't so",
        "chords": "G Gm G"
      },
      {
        "title": "Rollin STones - Gimme Shelter",
        "chords": "C# C#m C#"
      }
    ]
  },
  {
    "loop": "dom7 dom7 fifth fifth",
    "steps": [{"semitones":5,"quality":"same"},{"semitones":5,"quality":"same"},{"semitones":7,"quality":"same"},{"semitones":7,"quality":"same"}],
    "length": 4,
    "songCount": 267,
    "constraints": [
      "fifth",
      "dom7"
    ],
    "exampleChords": "E A D A E",
    "topSongs": [
      {
        "title": "ABBA - dancing queen",
        "chords": "E A D A E"
      },
      {
        "title": "Boston - more than a feeling",
        "chords": "D G C G D"
      },
      {
        "title": "Cyndi Lauper - Girls Just Want to Have Fun",
        "chords": "C# F# B F# C#"
      },
      {
        "title": "joel billy - piano man",
        "chords": "G C F C G"
      },
      {
        "title": "Billy Joel - Piano Man",
        "chords": "G C F C G"
      },
      {
        "title": "Cyndi Lauper - Time after Time",
        "chords": "G C F C G"
      },
      {
        "title": "van morrison - brown eyed girl",
        "chords": "D G C G D"
      },
      {
        "title": "nirvana - the man who sold the world",
        "chords": "C F A# F C"
      }
    ]
  },
  {
    "loop": "diatonic diatonic relative relative",
    "steps": [{"semitones":10,"quality":"major"},{"semitones":2,"quality":"minor"},{"semitones":3,"quality":"major"},{"semitones":9,"quality":"minor"}],
    "length": 4,
    "songCount": 246,
    "constraints": [
      "diatonic",
      "relative"
    ],
    "exampleChords": "F#m E F#m A F#m",
    "topSongs": [
      {
        "title": "radiohead - karma police",
        "chords": "Bm Am Bm D Bm"
      },
      {
        "title": "foo fighters - everlong",
        "chords": "D E D Bm D"
      },
      {
        "title": "ABBA - dancing queen",
        "chords": "F#m E F#m A F#m"
      },
      {
        "title": "toto - africa",
        "chords": "G#m A G#m B G#m"
      },
      {
        "title": "Depech Mode - enjoy the silence",
        "chords": "C#m B C#m E C#m"
      },
      {
        "title": "depeche mode - enjoy the silence",
        "chords": "C#m B C#m E C#m"
      },
      {
        "title": "dire straits - sultans of swing",
        "chords": "Gm Am Gm A# Gm"
      },
      {
        "title": "spice girls - wannabe",
        "chords": "F# E F# D#m F#"
      }
    ]
  },
  {
    "loop": "diatonic relative fifth",
    "steps": [{"semitones":2,"quality":"minor"},{"semitones":3,"quality":"major"},{"semitones":7,"quality":"same"}],
    "length": 3,
    "songCount": 244,
    "constraints": [
      "fifth",
      "diatonic",
      "relative"
    ],
    "exampleChords": "C Dm F C",
    "topSongs": [
      {
        "title": "radiohead - high and dry",
        "chords": "E F#m A E"
      },
      {
        "title": "Queen - bohemian rhapsody",
        "chords": "D# Fm G# D#"
      },
      {
        "title": "Queen - Queen Bohemian Rhapsody",
        "chords": "D# Fm G# D#"
      },
      {
        "title": "AC DC - back in black",
        "chords": "D Em G D"
      },
      {
        "title": "Depech Mode - enjoy the silence",
        "chords": "E F#m A E"
      },
      {
        "title": "depeche mode - enjoy the silence",
        "chords": "E F#m A E"
      },
      {
        "title": "pink floyd - the great gig in the sky",
        "chords": "F Gm A# F"
      },
      {
        "title": "green day - when i come around",
        "chords": "C# D#m F# C#"
      }
    ]
  },
  {
    "loop": "relative relative relative relative",
    "steps": [{"semitones":9,"quality":"minor"},{"semitones":3,"quality":"major"},{"semitones":9,"quality":"minor"},{"semitones":3,"quality":"major"}],
    "length": 4,
    "songCount": 234,
    "constraints": [
      "relative"
    ],
    "exampleChords": "C Am C Am C",
    "topSongs": [
      {
        "title": "weezer - buddy holly",
        "chords": "F#m A F#m A F#m"
      },
      {
        "title": "nirvana - dumb",
        "chords": "Em G Em G Em"
      },
      {
        "title": "nirvana - in bloom",
        "chords": "A# Gm A# Gm A#"
      },
      {
        "title": "toto - africa",
        "chords": "F#m A F#m A F#m"
      },
      {
        "title": "pink floyd - wish you were here",
        "chords": "G Em G Em G"
      },
      {
        "title": "dire straits - sultans of swing",
        "chords": "Dm F Dm F Dm"
      },
      {
        "title": "pearl jam - even flow",
        "chords": "A# Gm A# Gm A#"
      },
      {
        "title": "Black Sabbath - paranoid",
        "chords": "G Em G Em G"
      }
    ]
  },
  {
    "loop": "diatonic relative dom7",
    "steps": [{"semitones":10,"quality":"major"},{"semitones":9,"quality":"minor"},{"semitones":5,"quality":"same"}],
    "length": 3,
    "songCount": 199,
    "constraints": [
      "diatonic",
      "relative",
      "dom7"
    ],
    "exampleChords": "C#m B G#m C#m",
    "topSongs": [
      {
        "title": "radiohead - karma police",
        "chords": "D C Am D"
      },
      {
        "title": "REM - Losing My Religion",
        "chords": "G F Dm G"
      },
      {
        "title": "Boston - more than a feeling",
        "chords": "Am G Em Am"
      },
      {
        "title": "nirvana - polly",
        "chords": "D C Am D"
      },
      {
        "title": "led zepplin - stairway to heaven",
        "chords": "D C Am D"
      },
      {
        "title": "nirvana - territorial pissings",
        "chords": "F#m E C#m F#m"
      },
      {
        "title": "nirvana - pennyroyal tea",
        "chords": "A G Em A"
      },
      {
        "title": "Rollin STones - Sympathy for the Devil",
        "chords": "D C Am D"
      }
    ]
  },
  {
    "loop": "diatonic diatonic relative",
    "steps": [{"semitones":10,"quality":"same"},{"semitones":11,"quality":"minor"},{"semitones":3,"quality":"major"}],
    "length": 3,
    "songCount": 198,
    "constraints": [
      "diatonic",
      "relative"
    ],
    "exampleChords": "G F Em G",
    "topSongs": [
      {
        "title": "toto - africa",
        "chords": "F#m G#m A F#m"
      },
      {
        "title": "radiohead - subterranean homesick alien",
        "chords": "Em F G Em"
      },
      {
        "title": "Rollin STones - Gimme Shelter",
        "chords": "A G#m F#m A"
      },
      {
        "title": "rolling stones - gimme shelter",
        "chords": "A G#m F#m A"
      },
      {
        "title": "spice girls - wannabe",
        "chords": "D#m E F# D#m"
      },
      {
        "title": "Metallica - one",
        "chords": "G F Em G"
      },
      {
        "title": "Europe - The Final Countdown",
        "chords": "E D C#m E"
      },
      {
        "title": "kansas - dust in the wind",
        "chords": "F Em Dm F"
      }
    ]
  },
  {
    "loop": "diatonic diatonic diatonic dom7 dom7",
    "steps": [{"semitones":2,"quality":"same"},{"semitones":2,"quality":"minor"},{"semitones":10,"quality":"major"},{"semitones":5,"quality":"same"},{"semitones":5,"quality":"same"}],
    "length": 5,
    "songCount": 172,
    "constraints": [
      "diatonic",
      "dom7"
    ],
    "exampleChords": "C D Em D G C",
    "topSongs": [
      {
        "title": "earth wind fire - september",
        "chords": "A Bm A Bm E A"
      },
      {
        "title": "sublime - santeria",
        "chords": "A B A B E A"
      },
      {
        "title": "green day - when i come around",
        "chords": "B C# D#m C# F# B"
      },
      {
        "title": "Cyndi Lauper - Girls Just Want to Have Fun",
        "chords": "B C# B C# F# B"
      },
      {
        "title": "van morrison - brown eyed girl",
        "chords": "C D C D G C"
      },
      {
        "title": "prince - purple rain",
        "chords": "D E D E A D"
      },
      {
        "title": "dire straits - walk of life",
        "chords": "A B A B E A"
      },
      {
        "title": "nirvana - sliver",
        "chords": "F G F G C F"
      }
    ]
  },
  {
    "loop": "borrowed dom7",
    "steps": [{"semitones":7,"quality":"major"},{"semitones":5,"quality":"minor"}],
    "length": 2,
    "songCount": 160,
    "constraints": [
      "borrowed",
      "dom7"
    ],
    "exampleChords": "Am E Am",
    "topSongs": [
      {
        "title": "nirvana - lithium",
        "chords": "Am E Am"
      },
      {
        "title": "nirvana - in bloom",
        "chords": "Gm D Gm"
      },
      {
        "title": "dire straits - sultans of swing",
        "chords": "Dm A Dm"
      },
      {
        "title": "TLC - No Scrubs",
        "chords": "G#m D# G#m"
      },
      {
        "title": "doors the - people are strange",
        "chords": "Fm C Fm"
      },
      {
        "title": "AC DC - thunderstruck",
        "chords": "Em B Em"
      },
      {
        "title": "Metallica - master of puppets",
        "chords": "Em B Em"
      },
      {
        "title": "nirvana - the man who sold the world",
        "chords": "Dm A Dm"
      }
    ]
  },
  {
    "loop": "dom7 relative relative fifth",
    "steps": [{"semitones":5,"quality":"same"},{"semitones":9,"quality":"minor"},{"semitones":3,"quality":"major"},{"semitones":7,"quality":"same"}],
    "length": 4,
    "songCount": 155,
    "constraints": [
      "fifth",
      "relative",
      "dom7"
    ],
    "exampleChords": "D G Em G D",
    "topSongs": [
      {
        "title": "Depech Mode - enjoy the silence",
        "chords": "E A F#m A E"
      },
      {
        "title": "depeche mode - enjoy the silence",
        "chords": "E A F#m A E"
      },
      {
        "title": "led zepplin - stairway to heaven",
        "chords": "G C Am C G"
      },
      {
        "title": "fleetwood mac - rhiannon",
        "chords": "G C Am C G"
      },
      {
        "title": "U2 - One",
        "chords": "G C Am C G"
      },
      {
        "title": "spin doctors - two princes",
        "chords": "D G Em G D"
      },
      {
        "title": "Madonna - like a virgin",
        "chords": "F# B G#m B F#"
      },
      {
        "title": "Bryan Adams - heaven",
        "chords": "C F Dm F C"
      }
    ]
  },
  {
    "loop": "diatonic dom7 dom7 fifth dom7",
    "steps": [{"semitones":2,"quality":"same"},{"semitones":5,"quality":"same"},{"semitones":5,"quality":"same"},{"semitones":7,"quality":"same"},{"semitones":5,"quality":"same"}],
    "length": 5,
    "songCount": 152,
    "constraints": [
      "fifth",
      "diatonic",
      "dom7"
    ],
    "exampleChords": "D# F A# D# A# D#",
    "topSongs": [
      {
        "title": "foo fighters - my hero",
        "chords": "E F#m B E B E"
      },
      {
        "title": "Cyndi Lauper - Time after Time",
        "chords": "F G C F C F"
      },
      {
        "title": "pink floyd - hey you",
        "chords": "Dm Em Am Dm Am Dm"
      },
      {
        "title": "Beatles - let it be",
        "chords": "F G C F C F"
      },
      {
        "title": "Beatles - yellow submarine",
        "chords": "F Gm C F C F"
      },
      {
        "title": "spin doctors - two princes",
        "chords": "G A D G D G"
      },
      {
        "title": "Goo Goo Dolls - Iris",
        "chords": "G A D G D G"
      },
      {
        "title": "dire straits - walk of life",
        "chords": "A B E A E A"
      }
    ]
  },
  {
    "loop": "diatonic fifth dom7 fifth fifth",
    "steps": [{"semitones":10,"quality":"same"},{"semitones":7,"quality":"same"},{"semitones":5,"quality":"same"},{"semitones":7,"quality":"same"},{"semitones":7,"quality":"same"}],
    "length": 5,
    "songCount": 138,
    "constraints": [
      "fifth",
      "diatonic",
      "dom7"
    ],
    "exampleChords": "G F C F C G",
    "topSongs": [
      {
        "title": "Boston - more than a feeling",
        "chords": "D C G C G D"
      },
      {
        "title": "oasis - don't look back in anger",
        "chords": "G F C F C G"
      },
      {
        "title": "CCR - Bad Moon Rising",
        "chords": "A G D G D A"
      },
      {
        "title": "jackson michael - black or white",
        "chords": "B A E A E B"
      },
      {
        "title": "Goo Goo Dolls - Iris",
        "chords": "A G D G D A"
      },
      {
        "title": "dire straits - walk of life",
        "chords": "B A E A E B"
      },
      {
        "title": "Bryan Adams - heaven",
        "chords": "G F C F C G"
      },
      {
        "title": "who the - pinball wizard",
        "chords": "B A E A E B"
      }
    ]
  },
  {
    "loop": "dom7 fifth relative relative",
    "steps": [{"semitones":5,"quality":"same"},{"semitones":7,"quality":"same"},{"semitones":9,"quality":"minor"},{"semitones":3,"quality":"major"}],
    "length": 4,
    "songCount": 137,
    "constraints": [
      "fifth",
      "relative",
      "dom7"
    ],
    "exampleChords": "A D A F#m A",
    "topSongs": [
      {
        "title": "ABBA - dancing queen",
        "chords": "A D A F#m A"
      },
      {
        "title": "Black Sabbath - paranoid",
        "chords": "G C G Em G"
      },
      {
        "title": "Cyndi Lauper - Girls Just Want to Have Fun",
        "chords": "F# B F# D#m F#"
      },
      {
        "title": "joel billy - piano man",
        "chords": "C F C Am C"
      },
      {
        "title": "Billy Joel - Piano Man",
        "chords": "C F C Am C"
      },
      {
        "title": "Rollin STones - Gimme Shelter",
        "chords": "E A E C#m E"
      },
      {
        "title": "rolling stones - gimme shelter",
        "chords": "E A E C#m E"
      },
      {
        "title": "SmashMouth - All Star",
        "chords": "F# B F# D#m F#"
      }
    ]
  },
  {
    "loop": "diatonic fifth fifth dom7 fifth",
    "steps": [{"semitones":10,"quality":"same"},{"semitones":7,"quality":"same"},{"semitones":7,"quality":"same"},{"semitones":5,"quality":"same"},{"semitones":7,"quality":"same"}],
    "length": 5,
    "songCount": 115,
    "constraints": [
      "fifth",
      "diatonic",
      "dom7"
    ],
    "exampleChords": "E D A E A E",
    "topSongs": [
      {
        "title": "SmashMouth - All Star",
        "chords": "F# E B F# B F#"
      },
      {
        "title": "imbruglia natalie - torn",
        "chords": "C A# F C F C"
      },
      {
        "title": "pearl jam - jeremy",
        "chords": "A G D A D A"
      },
      {
        "title": "simple minds - dont you forget about me",
        "chords": "A G D A D A"
      },
      {
        "title": "Queen - under pressure",
        "chords": "A G D A D A"
      },
      {
        "title": "Eric Clapton - wonderful tonight",
        "chords": "D C G D G D"
      },
      {
        "title": "green day - longview",
        "chords": "A# G# D# A# D# A#"
      },
      {
        "title": "Chumba Wumba - Tubthumping",
        "chords": "A G D A D A"
      }
    ]
  },
  {
    "loop": "diatonic dom7 fifth dom7 dom7",
    "steps": [{"semitones":2,"quality":"same"},{"semitones":5,"quality":"same"},{"semitones":7,"quality":"same"},{"semitones":5,"quality":"same"},{"semitones":5,"quality":"same"}],
    "length": 5,
    "songCount": 109,
    "constraints": [
      "fifth",
      "diatonic",
      "dom7"
    ],
    "exampleChords": "D# F A# F A# D#",
    "topSongs": [
      {
        "title": "weezer - buddy holly",
        "chords": "G A D A D G"
      },
      {
        "title": "Cranberries - dreams",
        "chords": "A B E B E A"
      },
      {
        "title": "CCR - Have You Ever Seen The Rain",
        "chords": "F G C G C F"
      },
      {
        "title": "van morrison - brown eyed girl",
        "chords": "C D G D G C"
      },
      {
        "title": "Europe - The Final Countdown",
        "chords": "D E A E A D"
      },
      {
        "title": "Bon Jovi - Wanted Dead Or Alive",
        "chords": "C D G D G C"
      },
      {
        "title": "van halen - jump",
        "chords": "F G C G C F"
      },
      {
        "title": "CCR - Up Around The Bend",
        "chords": "G A D A D G"
      }
    ]
  },
  {
    "loop": "dom7 dom7 dom7 relative",
    "steps": [{"semitones":5,"quality":"major"},{"semitones":5,"quality":"same"},{"semitones":5,"quality":"same"},{"semitones":9,"quality":"minor"}],
    "length": 4,
    "songCount": 106,
    "constraints": [
      "relative",
      "dom7"
    ],
    "exampleChords": "G#m C# F# B G#m",
    "topSongs": [
      {
        "title": "a-ha - take on me",
        "chords": "Bm E A D Bm"
      },
      {
        "title": "Queen - bohemian rhapsody",
        "chords": "Gm Cm F A# Gm"
      },
      {
        "title": "Queen - Queen Bohemian Rhapsody",
        "chords": "Gm Cm F A# Gm"
      },
      {
        "title": "Europe - The Final Countdown",
        "chords": "Bm E A D Bm"
      },
      {
        "title": "Beatles - here comes the sun",
        "chords": "Bm E A D Bm"
      },
      {
        "title": "Bon Jovi - Wanted Dead Or Alive",
        "chords": "Am D G C Am"
      },
      {
        "title": "ABBA - fernando",
        "chords": "F#m Bm E A F#m"
      },
      {
        "title": "Beach Boys - kokomo",
        "chords": "Am Dm G C Am"
      }
    ]
  },
  {
    "loop": "diatonic dom7 diatonic fifth",
    "steps": [{"semitones":2,"quality":"minor"},{"semitones":5,"quality":"major"},{"semitones":10,"quality":"same"},{"semitones":7,"quality":"same"}],
    "length": 4,
    "songCount": 95,
    "constraints": [
      "fifth",
      "diatonic",
      "dom7"
    ],
    "exampleChords": "G Am D C G",
    "topSongs": [
      {
        "title": "radiohead - karma police",
        "chords": "Bm Am D Em Bm"
      },
      {
        "title": "dire straits - sultans of swing",
        "chords": "F Gm C A# F"
      },
      {
        "title": "Rollin STones - Sympathy for the Devil",
        "chords": "G A D C G"
      },
      {
        "title": "sublime - wrong way",
        "chords": "E F# B A E"
      },
      {
        "title": "morisette alanis - ironic",
        "chords": "B C#m F# E B"
      },
      {
        "title": "Beatles - while my guitar gently weeps",
        "chords": "D E Am G D"
      },
      {
        "title": "U2 - Sunday Bloody Sunday",
        "chords": "A#m G#m C# D#m A#m"
      },
      {
        "title": "Beatles - a day in the life",
        "chords": "A B E D A"
      }
    ]
  },
  {
    "loop": "borrowed fifth diatonic",
    "steps": [{"semitones":3,"quality":"same"},{"semitones":7,"quality":"same"},{"semitones":2,"quality":"same"}],
    "length": 3,
    "songCount": 94,
    "constraints": [
      "fifth",
      "diatonic",
      "borrowed"
    ],
    "exampleChords": "C D# A# C",
    "topSongs": [
      {
        "title": "police - every breath you take",
        "chords": "A C G A"
      },
      {
        "title": "pink floyd - comfortably numb",
        "chords": "A C G A"
      },
      {
        "title": "pink floyd - brain damage",
        "chords": "E G D E"
      },
      {
        "title": "Beatles - something",
        "chords": "D F C D"
      },
      {
        "title": "sublime - wrong way",
        "chords": "B D A B"
      },
      {
        "title": "rolling stones - you can't always get what you want",
        "chords": "D F C D"
      },
      {
        "title": "Beatles - i want to hold your hand",
        "chords": "A C G A"
      },
      {
        "title": "led zepplin - good times bad times",
        "chords": "B D A B"
      }
    ]
  },
  {
    "loop": "leadingTone leadingTone",
    "steps": [{"semitones":11,"quality":"dim"},{"semitones":1,"quality":"major"}],
    "length": 2,
    "songCount": 94,
    "constraints": [
      "leadingTone"
    ],
    "exampleChords": "F Edim F",
    "topSongs": [
      {
        "title": "nirvana - all apologies",
        "chords": "F# Fdim F#"
      },
      {
        "title": "Boston - more than a feeling",
        "chords": "G F#dim G"
      },
      {
        "title": "joel billy - piano man",
        "chords": "C Bdim C"
      },
      {
        "title": "fleetwood mac - landslide",
        "chords": "Adim A# Adim"
      },
      {
        "title": "nirvana - lounge act",
        "chords": "G# Gdim G#"
      },
      {
        "title": "doors the - touch me",
        "chords": "C Bdim C"
      },
      {
        "title": "ABBA - fernando",
        "chords": "G#dim A G#dim"
      },
      {
        "title": "BareNaked Ladies - One Week",
        "chords": "A G#dim A"
      }
    ]
  },
  {
    "loop": "diatonic diatonic diatonic fifth fifth",
    "steps": [{"semitones":10,"quality":"same"},{"semitones":2,"quality":"same"},{"semitones":10,"quality":"same"},{"semitones":7,"quality":"same"},{"semitones":7,"quality":"same"}],
    "length": 5,
    "songCount": 92,
    "constraints": [
      "fifth",
      "diatonic"
    ],
    "exampleChords": "A G A G D A",
    "topSongs": [
      {
        "title": "red hot chilli peppers - under the bridge",
        "chords": "B C#m B A E B"
      },
      {
        "title": "SmashMouth - All Star",
        "chords": "F# G#m F# E B F#"
      },
      {
        "title": "rage against the machine - bulls on parade",
        "chords": "E D E D A E"
      },
      {
        "title": "Rollin STones - Sympathy for the Devil",
        "chords": "D C D C G D"
      },
      {
        "title": "smashing pumpkins - today",
        "chords": "B A B A E B"
      },
      {
        "title": "Queen - under pressure",
        "chords": "A G A G D A"
      },
      {
        "title": "houston whitney - i will always love you",
        "chords": "E D E D A E"
      },
      {
        "title": "prince - kiss",
        "chords": "E D E D A E"
      }
    ]
  },
  {
    "loop": "borrowed dom7 diatonic",
    "steps": [{"semitones":9,"quality":"same"},{"semitones":5,"quality":"same"},{"semitones":10,"quality":"same"}],
    "length": 3,
    "songCount": 92,
    "constraints": [
      "diatonic",
      "borrowed",
      "dom7"
    ],
    "exampleChords": "G E A G",
    "topSongs": [
      {
        "title": "nirvana - the man who sold the world",
        "chords": "C A Dm C"
      },
      {
        "title": "Europe - The Final Countdown",
        "chords": "G E A G"
      },
      {
        "title": "mamas and the papas - california dreaming",
        "chords": "C A Dm C"
      },
      {
        "title": "Bee Bees - how deep is your love",
        "chords": "D# C Fm D#"
      },
      {
        "title": "beegees - how deep is your love",
        "chords": "D# C Fm D#"
      },
      {
        "title": "Beatles - something",
        "chords": "F D G F"
      },
      {
        "title": "CCR - Proud Mary",
        "chords": "G E A G"
      },
      {
        "title": "Bon Jovi - Wanted Dead Or Alive",
        "chords": "F D G F"
      }
    ]
  },
  {
    "loop": "diatonic diatonic parallel",
    "steps": [{"semitones":10,"quality":"major"},{"semitones":2,"quality":"same"},{"semitones":0,"quality":"minor"}],
    "length": 3,
    "songCount": 84,
    "constraints": [
      "diatonic",
      "parallel"
    ],
    "exampleChords": "A#m G# A# A#m",
    "topSongs": [
      {
        "title": "toto - africa",
        "chords": "F#m G#m F# F#m"
      },
      {
        "title": "pearl jam - even flow",
        "chords": "D C Dm D"
      },
      {
        "title": "pearl jam - alive",
        "chords": "Bm A B Bm"
      },
      {
        "title": "kansas - dust in the wind",
        "chords": "D Em Dm D"
      },
      {
        "title": "Rollin STones - Sympathy for the Devil",
        "chords": "D C Dm D"
      },
      {
        "title": "SEAL - kiss from a rose",
        "chords": "G#m F# G# G#m"
      },
      {
        "title": "wonder stevie - isn't she lovely",
        "chords": "Dm C D Dm"
      },
      {
        "title": "REM - Shiny Happy People",
        "chords": "A G Am A"
      }
    ]
  },
  {
    "loop": "diatonic diatonic diatonic dom7 relative",
    "steps": [{"semitones":10,"quality":"major"},{"semitones":2,"quality":"minor"},{"semitones":10,"quality":"major"},{"semitones":5,"quality":"same"},{"semitones":9,"quality":"minor"}],
    "length": 5,
    "songCount": 82,
    "constraints": [
      "diatonic",
      "relative",
      "dom7"
    ],
    "exampleChords": "Gm F Gm F A# Gm",
    "topSongs": [
      {
        "title": "red hot chilli peppers - under the bridge",
        "chords": "C#m B C#m B E C#m"
      },
      {
        "title": "radiohead - fake plastic trees",
        "chords": "Bm A Bm A D Bm"
      },
      {
        "title": "pearl jam - even flow",
        "chords": "Bm Am G Am D Bm"
      },
      {
        "title": "pink floyd - hey you",
        "chords": "Em F Em D G Em"
      },
      {
        "title": "Aqua - barbie girl",
        "chords": "F#m E F#m E A F#m"
      },
      {
        "title": "Madonna - like a virgin",
        "chords": "G#m F# G#m F# B G#m"
      },
      {
        "title": "Beatles - i want to hold your hand",
        "chords": "Am G Am G C Am"
      },
      {
        "title": "earth wind fire - boogie wonderland",
        "chords": "Am Gm Am Gm C Am"
      }
    ]
  },
  {
    "loop": "borrowed borrowed borrowed borrowed",
    "steps": [{"semitones":9,"quality":"same"},{"semitones":3,"quality":"same"},{"semitones":9,"quality":"same"},{"semitones":3,"quality":"same"}],
    "length": 4,
    "songCount": 81,
    "constraints": [
      "borrowed"
    ],
    "exampleChords": "G# F G# F G#",
    "topSongs": [
      {
        "title": "jackson michael - billie jean",
        "chords": "B D B D B"
      },
      {
        "title": "weezer - buddy holly",
        "chords": "D F# D F# D"
      },
      {
        "title": "nirvana - dumb",
        "chords": "A C A C A"
      },
      {
        "title": "Blur - song 2",
        "chords": "G# F G# F G#"
      },
      {
        "title": "doors the - people are strange",
        "chords": "C G# C G# C"
      },
      {
        "title": "Black Sabbath - ironman",
        "chords": "D# B D# F# D#"
      },
      {
        "title": "Tears for Fears - Head Over Heels",
        "chords": "A C A C A"
      },
      {
        "title": "Blur - girls and boys",
        "chords": "D# G D# G D#"
      }
    ]
  },
  {
    "loop": "borrowed borrowed diatonic diatonic",
    "steps": [{"semitones":9,"quality":"same"},{"semitones":3,"quality":"same"},{"semitones":2,"quality":"minor"},{"semitones":10,"quality":"major"}],
    "length": 4,
    "songCount": 79,
    "constraints": [
      "diatonic",
      "borrowed"
    ],
    "exampleChords": "E C# E F#m E",
    "topSongs": [
      {
        "title": "Eric Clapton - cocaine",
        "chords": "G E G A G"
      },
      {
        "title": "SEAL - kiss from a rose",
        "chords": "E G# E D#m E"
      },
      {
        "title": "Tears for Fears - Head Over Heels",
        "chords": "A C A Bm A"
      },
      {
        "title": "Beatles - something",
        "chords": "D F D C D"
      },
      {
        "title": "stone temple pilots - plush",
        "chords": "C D# C Bm C"
      },
      {
        "title": "jamiroquai - virtual insanity",
        "chords": "G# B G# A# G#"
      },
      {
        "title": "Alice In Chains - rooster",
        "chords": "G# F G# A# G#"
      },
      {
        "title": "Alice In Chains - no excuses",
        "chords": "B D B A B"
      }
    ]
  },
  {
    "loop": "diatonic fifth relative",
    "steps": [{"semitones":2,"quality":"minor"},{"semitones":7,"quality":"same"},{"semitones":3,"quality":"major"}],
    "length": 3,
    "songCount": 78,
    "constraints": [
      "fifth",
      "diatonic",
      "relative"
    ],
    "exampleChords": "C# D#m A#m C#",
    "topSongs": [
      {
        "title": "nirvana - rape me",
        "chords": "G Am Em G"
      },
      {
        "title": "Metallica - one",
        "chords": "G Am Em G"
      },
      {
        "title": "Bon Jovi - it's my life",
        "chords": "A# Cm Gm A#"
      },
      {
        "title": "kansas - dust in the wind",
        "chords": "G Am Em G"
      },
      {
        "title": "depeche mode - personal jesus",
        "chords": "A# Cm Gm A#"
      },
      {
        "title": "Depech Mode - personal jesus",
        "chords": "A# Cm Gm A#"
      },
      {
        "title": "ABBA - waterloo",
        "chords": "D Em Bm D"
      },
      {
        "title": "U2 - Sunday Bloody Sunday",
        "chords": "C# D#m A#m C#"
      }
    ]
  },
  {
    "loop": "dom7 relative fifth relative",
    "steps": [{"semitones":5,"quality":"same"},{"semitones":9,"quality":"minor"},{"semitones":7,"quality":"same"},{"semitones":3,"quality":"major"}],
    "length": 4,
    "songCount": 77,
    "constraints": [
      "fifth",
      "relative",
      "dom7"
    ],
    "exampleChords": "G C Am Em G",
    "topSongs": [
      {
        "title": "aerosmith - dream on",
        "chords": "Fm A#m C# G# Fm"
      },
      {
        "title": "joel billy - piano man",
        "chords": "C F Dm Am C"
      },
      {
        "title": "ABBA - waterloo",
        "chords": "D G Em Bm D"
      },
      {
        "title": "Beatles - lucy in the sky with diamonds",
        "chords": "F A# Gm Dm F"
      },
      {
        "title": "Queen - the show must go on",
        "chords": "D G Em Bm D"
      },
      {
        "title": "nirvana - school",
        "chords": "G C Am Em G"
      },
      {
        "title": "Metallica - fade to black",
        "chords": "Em Am C G Em"
      },
      {
        "title": "osbourne ozzy - mr crowley",
        "chords": "Am Dm F C Am"
      }
    ]
  },
  {
    "loop": "borrowed diatonic diatonic",
    "steps": [{"semitones":8,"quality":"same"},{"semitones":2,"quality":"same"},{"semitones":2,"quality":"same"}],
    "length": 3,
    "songCount": 74,
    "constraints": [
      "diatonic",
      "borrowed"
    ],
    "exampleChords": "C G# A# C",
    "topSongs": [
      {
        "title": "Metallica - master of puppets",
        "chords": "C E D C"
      },
      {
        "title": "nirvana - pennyroyal tea",
        "chords": "D A# C D"
      },
      {
        "title": "SEAL - kiss from a rose",
        "chords": "G# E F# G#"
      },
      {
        "title": "rush - tom sawyer",
        "chords": "C E D C"
      },
      {
        "title": "simon %26 garfunkel - mrs. robinson",
        "chords": "D F# E D"
      },
      {
        "title": "jamiroquai - virtual insanity",
        "chords": "F# D# Fm F#"
      },
      {
        "title": "garbage - only happy when it rains",
        "chords": "A F# G#m A"
      },
      {
        "title": "Sheryl Crow - All I Wanna Do",
        "chords": "G# E F# G#"
      }
    ]
  },
  {
    "loop": "diatonic dom7 fifth dom7 relative",
    "steps": [{"semitones":10,"quality":"major"},{"semitones":5,"quality":"same"},{"semitones":7,"quality":"same"},{"semitones":5,"quality":"same"},{"semitones":9,"quality":"minor"}],
    "length": 5,
    "songCount": 67,
    "constraints": [
      "fifth",
      "diatonic",
      "relative",
      "dom7"
    ],
    "exampleChords": "Bm A D A D Bm",
    "topSongs": [
      {
        "title": "ABBA - dancing queen",
        "chords": "F#m E A E A F#m"
      },
      {
        "title": "Boston - more than a feeling",
        "chords": "Em D G D G Em"
      },
      {
        "title": "pink floyd - hey you",
        "chords": "Em D G D G Em"
      },
      {
        "title": "goo goo dolls - iris",
        "chords": "Em D G D G Em"
      },
      {
        "title": "fatboy slim - praise you",
        "chords": "G#m F# B F# B G#m"
      },
      {
        "title": "ABBA - chiquitita",
        "chords": "Bm A D A D Bm"
      },
      {
        "title": "MatchBox 20 - Push",
        "chords": "D#m C# F# C# F# D#m"
      },
      {
        "title": "Rollin STones - Satisfaction",
        "chords": "F#m E A E A F#m"
      }
    ]
  }
];