/**
 * Test Practice Mode
 *
 * Loads directly into PracticeFrameDisplay with cached data.
 * Run with: npm run dev:test
 *
 * This bypasses YouTube import and loads cached frames/audio directly.
 * Now supports MIDI keyboard input for tracking performance!
 *
 * Audio comes from:
 * - YouTube video (through PracticeFrameDisplay)
 * - Your physical keyboard (external audio, not generated by app)
 */

import { useState, useEffect, useRef, useCallback } from 'react';
import { WebMidi } from 'webmidi';
import { PracticeFrameDisplay } from '../components/PracticeFrameDisplay';
import { VisualKeyboard } from '../components/VisualKeyboard';
import { TEST_VIDEO_ID, TEST_SEGMENT, TEST_FRAME_TIMES } from './fixtures/testSegment';
import type { MelodyNote } from '../utils/midiParser';
import { loadConfig } from '../config/AppConfig';
import { analyzeMultipleFrames, checkOCRStatus, type SheetMusicAnalysis } from '../core/SheetMusicOCR';
import { convertOcrNotesToMelody, countMeasures, inferTempo } from '../utils/timingConverter';

// Simple performance stats (no tightening algorithm needed)
export interface SimpleStats {
  hits: number;
  misses: number;
  extras: number;
}

export function TestPracticeMode() {
  // ALL HOOKS MUST BE BEFORE ANY CONDITIONAL RETURNS
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [frames, setFrames] = useState<Map<number, string>>(new Map());
  const [audioUrl, setAudioUrl] = useState<string | null>(null);
  const [notes, setNotes] = useState<MelodyNote[]>([]);
  const [status, setStatus] = useState('Initializing...');
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [width, setWidth] = useState(1200);

  // MIDI state - just for tracking, keyboard makes its own sound
  const [midiStatus, setMidiStatus] = useState<string>('Initializing MIDI...');
  const [midiPressedKeys, setMidiPressedKeys] = useState<Set<number>>(new Set());
  const [stats, setStats] = useState<SimpleStats>({ hits: 0, misses: 0, extras: 0 });

  // Wait mode - video pauses until correct note is played
  const [waitMode, setWaitMode] = useState(false);
  const [isWaiting, setIsWaiting] = useState(false);
  const waitingForNotesRef = useRef<Set<number>>(new Set()); // MIDI notes we're waiting for (chord)
  const waitingNoteIndicesRef = useRef<Set<number>>(new Set()); // Indices of notes we're waiting for
  const playedWhileWaitingRef = useRef<Set<number>>(new Set()); // Notes played so far while waiting
  const lastWaitNoteIndexRef = useRef<number>(-1); // Track which note we last paused for

  const config = loadConfig();
  const containerRef = useRef<HTMLDivElement>(null);
  const lastScreenshotTime = useRef(0);
  const screenshotEnabled = useRef(true);

  // Track current playback time for MIDI note matching
  const practiceTimeRef = useRef<number>(0);

  // Track which notes have been hit (for miss detection)
  const hitNoteIndicesRef = useRef<Set<number>>(new Set());
  const lastCheckedNoteIndexRef = useRef<number>(-1);

  // Refs to always point to latest handlers (avoids stale closure in IPC MIDI listeners)
  const handleNoteOnRef = useRef<((data: { note: number; velocity: number }) => void) | null>(null);
  const handleNoteOffRef = useRef<((data: { note: number }) => void) | null>(null);

  // Screenshot helper - captures at key moments
  const captureScreenshot = useCallback(async (label: string) => {
    if (!screenshotEnabled.current || !window.electronAPI?.debugScreenshot) return;
    try {
      await window.electronAPI.debugScreenshot(label);
    } catch (err) {
      console.error('[TestMode] Screenshot failed:', err);
    }
  }, []);

  // Handle play state changes
  const handlePlayStateChange = useCallback((playing: boolean) => {
    setIsPlaying(playing);
    console.log('[TestMode] Play state:', playing);
    captureScreenshot(playing ? 'play_start' : 'play_stop');
  }, [captureScreenshot]);

  // Handle time updates - also update practiceTimeRef for MIDI matching
  const handleTimeUpdate = useCallback((time: number) => {
    setCurrentTime(time);
    practiceTimeRef.current = time;
  }, []);

  // Callback to request pause/resume from PracticeFrameDisplay
  const pausePlaybackRef = useRef<(() => void) | null>(null);
  const resumePlaybackRef = useRef<(() => void) | null>(null);

  // MIDI note on handler - just track hits/extras, keyboard makes its own sound
  const handleNoteOn = useCallback((data: { note: number; velocity: number }) => {
    const pressedMidiKey = data.note;
    console.log('[TestMode MIDI] Note ON', { midi: pressedMidiKey, velocity: data.velocity });

    // Add to pressed keys for visual feedback
    setMidiPressedKeys((prev) => new Set(prev).add(pressedMidiKey));

    if (notes.length === 0) return;

    // Check if we're waiting for notes (wait mode) - handles chords
    if (isWaiting && waitingForNotesRef.current.size > 0) {
      if (waitingForNotesRef.current.has(pressedMidiKey)) {
        // Correct note! Add to played set
        playedWhileWaitingRef.current.add(pressedMidiKey);

        console.log('[TestMode MIDI] Correct note played!', {
          pressed: pressedMidiKey,
          played: Array.from(playedWhileWaitingRef.current),
          needed: Array.from(waitingForNotesRef.current)
        });

        // Check if all chord notes have been played
        const allPlayed = Array.from(waitingForNotesRef.current).every(
          note => playedWhileWaitingRef.current.has(note)
        );

        if (allPlayed) {
          console.log('[TestMode MIDI] All chord notes played! Resuming playback.');
          // Mark all notes as hit
          waitingNoteIndicesRef.current.forEach(idx => {
            hitNoteIndicesRef.current.add(idx);
          });
          const hitCount = waitingNoteIndicesRef.current.size;

          // Reset waiting state
          setIsWaiting(false);
          waitingForNotesRef.current.clear();
          waitingNoteIndicesRef.current.clear();
          playedWhileWaitingRef.current.clear();

          resumePlaybackRef.current?.();
          // Record all chord notes as hits
          setStats(prev => ({ ...prev, hits: prev.hits + hitCount }));
        }
        return;
      } else {
        // Wrong note while waiting - just ignore (don't count as extra, they're trying)
        console.log('[TestMode MIDI] Wrong note while waiting', {
          pressed: pressedMidiKey,
          expected: Array.from(waitingForNotesRef.current)
        });
        return;
      }
    }

    const time = practiceTimeRef.current;

    // Find currently ACTIVE note
    const activeNoteIndex = notes.findIndex((n) => {
      const noteStart = n.time;
      const noteEnd = n.time + n.duration;
      return time >= noteStart && time < noteEnd;
    });

    const isInGap = activeNoteIndex === -1;
    const currentNote = activeNoteIndex >= 0 ? notes[activeNoteIndex] : null;

    // If in a gap, this is an EXTRA press
    if (isInGap) {
      console.log('[TestMode MIDI] EXTRA - no note expected at', time.toFixed(2));
      setStats(prev => ({ ...prev, extras: prev.extras + 1 }));
      return;
    }

    // HIT: Active note being played
    hitNoteIndicesRef.current.add(activeNoteIndex);

    console.log('[TestMode MIDI] HIT', {
      pressed: pressedMidiKey,
      expected: currentNote!.midi,
      name: currentNote!.name,
      noteIndex: activeNoteIndex
    });

    setStats(prev => ({ ...prev, hits: prev.hits + 1 }));
  }, [notes, isWaiting]);

  // MIDI note off handler
  const handleNoteOff = useCallback((data: { note: number }) => {
    console.log('[TestMode MIDI] Note OFF', { midi: data.note });
    setMidiPressedKeys((prev) => {
      const next = new Set(prev);
      next.delete(data.note);
      return next;
    });
  }, []);

  // Keep refs updated with latest handlers
  useEffect(() => {
    handleNoteOnRef.current = handleNoteOn;
    handleNoteOffRef.current = handleNoteOff;
  }, [handleNoteOn, handleNoteOff]);

  // Track container width
  useEffect(() => {
    const updateWidth = () => {
      if (containerRef.current) {
        setWidth(containerRef.current.clientWidth - 40);
      }
    };
    updateWidth();
    window.addEventListener('resize', updateWidth);
    return () => window.removeEventListener('resize', updateWidth);
  }, []);

  // Set up WebMIDI (browser-based, no native modules needed)
  useEffect(() => {
    console.log('[TestMode] Initializing WebMIDI...');

    WebMidi.enable()
      .then(() => {
        console.log('[TestMode] WebMIDI enabled!');
        console.log('[TestMode] MIDI inputs:', WebMidi.inputs.map(i => i.name));
        console.log('[TestMode] MIDI outputs:', WebMidi.outputs.map(o => o.name));

        if (WebMidi.inputs.length === 0) {
          setMidiStatus('No MIDI devices found');
          return;
        }

        // Use the first input (or you could let user choose)
        const input = WebMidi.inputs[0];
        setMidiStatus(`Connected: ${input.name}`);
        console.log('[TestMode] Listening to:', input.name);

        // Listen for note on
        input.addListener('noteon', (e) => {
          if (handleNoteOnRef.current) {
            handleNoteOnRef.current({
              note: e.note.number,
              velocity: Math.round(e.note.attack * 127), // Convert 0-1 to 0-127
            });
          }
        });

        // Listen for note off
        input.addListener('noteoff', (e) => {
          if (handleNoteOffRef.current) {
            handleNoteOffRef.current({ note: e.note.number });
          }
        });
      })
      .catch((err) => {
        console.error('[TestMode] WebMIDI failed:', err);
        setMidiStatus(`MIDI Error: ${err.message}`);
      });

    return () => {
      // Cleanup - remove all listeners
      WebMidi.inputs.forEach((input) => {
        input.removeListener();
      });
    };
  }, []);

  // Miss detection - check for notes that passed without being hit
  // IMPORTANT: Don't count misses when in wait mode (we're paused waiting for input)
  useEffect(() => {
    if (!isPlaying || notes.length === 0 || isWaiting) return;

    const interval = setInterval(() => {
      // Double-check we're not waiting (state might have changed)
      if (isWaiting) return;

      const time = practiceTimeRef.current;
      const lastChecked = lastCheckedNoteIndexRef.current;
      const hitNotes = hitNoteIndicesRef.current;
      let missCount = 0;

      // Find notes that have ended and weren't hit
      for (let i = lastChecked + 1; i < notes.length; i++) {
        const note = notes[i];
        const noteEnd = note.time + note.duration;

        if (noteEnd < time) {
          // Note window has passed
          if (!hitNotes.has(i)) {
            // This note was MISSED
            missCount++;
            console.log('[TestMode] MISS detected', {
              noteIndex: i,
              midi: note.midi,
              name: note.name,
              noteEnd: noteEnd.toFixed(2),
              currentTime: time.toFixed(2)
            });
          }
          lastCheckedNoteIndexRef.current = i;
        } else {
          // Haven't reached this note's end yet
          break;
        }
      }

      if (missCount > 0) {
        setStats(prev => ({ ...prev, misses: prev.misses + missCount }));
      }
    }, 100); // Check every 100ms

    return () => clearInterval(interval);
  }, [isPlaying, notes, isWaiting]);

  // Wait mode - pause when entering a note's window (handles chords)
  useEffect(() => {
    if (!waitMode || !isPlaying || isWaiting || notes.length === 0) return;

    const time = practiceTimeRef.current;

    // Find ALL notes currently active (handles chords)
    const activeNotes: { index: number; note: typeof notes[0] }[] = [];
    notes.forEach((n, i) => {
      const noteStart = n.time;
      const noteEnd = n.time + n.duration;
      if (time >= noteStart && time < noteEnd) {
        activeNotes.push({ index: i, note: n });
      }
    });

    if (activeNotes.length === 0) return;

    // Check if we've already processed this group (use first note's index as reference)
    const firstNoteIndex = activeNotes[0].index;
    if (firstNoteIndex === lastWaitNoteIndexRef.current) return;

    // Filter to notes that haven't been hit yet
    const unhitNotes = activeNotes.filter(({ index }) => !hitNoteIndicesRef.current.has(index));

    if (unhitNotes.length > 0) {
      console.log('[TestMode] Wait mode: Pausing for chord', {
        noteCount: unhitNotes.length,
        notes: unhitNotes.map(({ note }) => ({ midi: note.midi, name: note.name })),
        time: time.toFixed(2)
      });

      lastWaitNoteIndexRef.current = firstNoteIndex;

      // Set up waiting for all chord notes
      waitingForNotesRef.current = new Set(unhitNotes.map(({ note }) => note.midi));
      waitingNoteIndicesRef.current = new Set(unhitNotes.map(({ index }) => index));
      playedWhileWaitingRef.current.clear();

      setIsWaiting(true);
      pausePlaybackRef.current?.();
    }
  }, [waitMode, isPlaying, isWaiting, currentTime, notes]);

  // Reset hit tracking when playback restarts
  useEffect(() => {
    if (!isPlaying) {
      // Reset tracking when stopped
      hitNoteIndicesRef.current.clear();
      lastCheckedNoteIndexRef.current = -1;
    }
  }, [isPlaying]);

  // Capture screenshots during playback (every 0.5 seconds)
  useEffect(() => {
    if (isPlaying && currentTime - lastScreenshotTime.current >= 0.5) {
      lastScreenshotTime.current = currentTime;
      captureScreenshot(`t${currentTime.toFixed(1)}`);
    }
  }, [isPlaying, currentTime, captureScreenshot]);

  // Load cached data on mount
  useEffect(() => {
    const loadTestData = async () => {
      try {
        if (!window.electronAPI) {
          throw new Error('electronAPI not available - must run in Electron');
        }

        // Check OCR availability
        setStatus('Checking OCR status...');
        const ocrStatus = await checkOCRStatus();
        if (!ocrStatus.available) {
          throw new Error(`OCR not available: ${ocrStatus.error}`);
        }

        // Load frames first (needed for OCR)
        setStatus('Loading frames...');
        const outputDir = await window.electronAPI.youtubeGetOutputDir();
        const frameMap = new Map<number, string>();

        for (const time of TEST_FRAME_TIMES) {
          const seconds = Math.floor(time);
          const centiseconds = Math.round((time - seconds) * 100);
          const frameName = `frame_${seconds}_${centiseconds.toString().padStart(2, '0')}.jpg`;
          const framePath = `${outputDir}/frames/${TEST_VIDEO_ID}/${frameName}`;

          const dataUrl = await window.electronAPI.readImageFile(framePath);
          if (dataUrl) {
            const relativeTime = time - TEST_SEGMENT.startTime;
            frameMap.set(relativeTime, dataUrl);
          }
        }

        console.log(`[TestMode] Loaded ${frameMap.size} frames`);
        setFrames(frameMap);

        // Check for cached OCR results
        const ocrCacheKey = `${TEST_VIDEO_ID}_ocr_${TEST_SEGMENT.startTime}_${TEST_SEGMENT.endTime}`;
        let ocrResult: SheetMusicAnalysis | null = null;

        const cachedOcr = await window.electronAPI.analysisCacheLoad(ocrCacheKey);
        if (cachedOcr && cachedOcr.notes && cachedOcr.notes.length > 0) {
          console.log(`[TestMode] Using cached OCR results: ${cachedOcr.notes.length} notes`);
          ocrResult = cachedOcr as SheetMusicAnalysis;
        } else {
          // Run OCR on frames
          setStatus('Running sheet music OCR (Claude Vision)...');
          console.log('[TestMode] Running OCR on frames...');
          ocrResult = await analyzeMultipleFrames(frameMap);
          console.log(`[TestMode] OCR found ${ocrResult.notes.length} notes`);

          // Cache the OCR results
          if (ocrResult.notes.length > 0) {
            await window.electronAPI.analysisCacheSave(ocrCacheKey, ocrResult);
            console.log('[TestMode] OCR results cached');
          }
        }

        // Convert OCR notes to MelodyNote format
        if (ocrResult && ocrResult.notes.length > 0) {
          const segmentDuration = TEST_SEGMENT.endTime - TEST_SEGMENT.startTime;
          const measureCount = countMeasures(ocrResult.notes);
          const beatsPerMeasure = ocrResult.timeSignature.numerator;

          // Infer tempo from segment duration and measure count
          const inferredTempo = ocrResult.tempo || inferTempo(segmentDuration, measureCount, beatsPerMeasure);
          console.log(`[TestMode] Using tempo: ${inferredTempo} BPM (${measureCount} measures, ${beatsPerMeasure} beats/measure)`);

          const melodyNotes = convertOcrNotesToMelody(ocrResult.notes, {
            beatsPerMeasure,
            tempo: inferredTempo,
            segmentStartTime: 0, // Relative timing
          });

          console.log(`[TestMode] Converted to ${melodyNotes.length} melody notes`);
          setNotes(melodyNotes);
        } else {
          console.warn('[TestMode] No OCR notes found, falling back to pitch detection');
          // Fallback to pitch detection if OCR fails
          const cachedAnalysis = await window.electronAPI.analysisCacheLoad(TEST_VIDEO_ID);
          if (cachedAnalysis?.notes) {
            const segmentNotes: MelodyNote[] = cachedAnalysis.notes
              .filter((n: any) => n.startTime >= TEST_SEGMENT.startTime && n.startTime < TEST_SEGMENT.endTime)
              .map((n: any) => ({
                midi: n.midi,
                name: n.noteName,
                time: n.startTime - TEST_SEGMENT.startTime,
                duration: n.duration,
                velocity: 80,
              }));
            setNotes(segmentNotes);
          }
        }

        // Load audio
        setStatus('Loading audio...');
        const audioPath = `${outputDir}/${TEST_VIDEO_ID}.wav`;
        const audioBase64 = await window.electronAPI.readAudioFile(audioPath);
        if (audioBase64) {
          const binaryString = atob(audioBase64);
          const bytes = new Uint8Array(binaryString.length);
          for (let i = 0; i < binaryString.length; i++) {
            bytes[i] = binaryString.charCodeAt(i);
          }
          const blob = new Blob([bytes], { type: 'audio/wav' });
          setAudioUrl(URL.createObjectURL(blob));
        }

        setStatus('Ready');
        setLoading(false);
        console.log('[TestMode] All data loaded successfully');

        // Reset and capture initial screenshot
        if (window.electronAPI?.debugScreenshotReset) {
          await window.electronAPI.debugScreenshotReset();
        }
        // Short delay to let UI render
        setTimeout(async () => {
          if (window.electronAPI?.debugScreenshot) {
            await window.electronAPI.debugScreenshot('ready');
          }
        }, 500);

      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        console.error('[TestMode] Error:', msg);
        setError(msg);
        setLoading(false);
      }
    };

    loadTestData();
  }, []);

  // Calculate note range (always, not conditionally)
  const noteRange = notes.length > 0
    ? {
        min: Math.min(...notes.map(n => n.midi)) - 5,
        max: Math.max(...notes.map(n => n.midi)) + 5
      }
    : { min: 48, max: 72 };

  // Find current note(s) for keyboard highlighting (expected notes from score)
  const currentNotes = notes.filter(
    n => currentTime >= n.time && currentTime < n.time + n.duration
  );
  const currentNoteMidi = currentNotes.length > 0 ? currentNotes[0].midi : null;
  const expectedKeys = new Set(currentNotes.map(n => n.midi));

  // NOW we can do conditional returns (after all hooks)
  if (loading) {
    return (
      <div style={{
        padding: 40,
        backgroundColor: '#1a1a1a',
        color: '#fff',
        height: '100vh',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
      }}>
        <h1>Test Practice Mode</h1>
        <p style={{ color: '#888' }}>{status}</p>
        <p style={{ color: '#666', fontSize: 12 }}>
          Video: {TEST_VIDEO_ID}<br/>
          Segment: {TEST_SEGMENT.startTime}s - {TEST_SEGMENT.endTime}s
        </p>
      </div>
    );
  }

  if (error) {
    return (
      <div style={{
        padding: 40,
        backgroundColor: '#1a1a1a',
        color: '#fff',
        height: '100vh',
      }}>
        <h1 style={{ color: '#f44' }}>Test Mode Error</h1>
        <p>{error}</p>
        <p style={{ color: '#888', marginTop: 20 }}>
          Make sure you have cached data for video {TEST_VIDEO_ID}.<br/>
          Run the app normally first and import a YouTube video to create the cache.
        </p>
      </div>
    );
  }

  return (
    <div
      ref={containerRef}
      style={{
        backgroundColor: '#1a1a1a',
        color: '#fff',
        height: '100vh',
        display: 'flex',
        flexDirection: 'column',
        padding: 20,
        overflow: 'hidden',
      }}
    >
      {/* Header */}
      <div style={{ marginBottom: 10, flexShrink: 0, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h2 style={{ margin: 0, color: '#4CAF50' }}>Test Practice Mode + MIDI</h2>
          <p style={{ margin: '5px 0', color: '#888', fontSize: 12 }}>
            {notes.length} notes | {frames.size} frames | t={currentTime.toFixed(1)}s | {isPlaying ? 'PLAYING' : 'PAUSED'} | {midiStatus}
          </p>
        </div>
        <div style={{ display: 'flex', gap: 10 }}>
          <button
            onClick={() => captureScreenshot('manual')}
            style={{ padding: '8px 16px', backgroundColor: '#2196F3', color: '#fff', border: 'none', borderRadius: 4, cursor: 'pointer' }}
          >
            Screenshot
          </button>
          <button
            onClick={() => { screenshotEnabled.current = !screenshotEnabled.current; }}
            style={{ padding: '8px 16px', backgroundColor: screenshotEnabled.current ? '#4CAF50' : '#666', color: '#fff', border: 'none', borderRadius: 4, cursor: 'pointer' }}
          >
            {screenshotEnabled.current ? 'Auto-capture ON' : 'Auto-capture OFF'}
          </button>
          <button
            onClick={() => {
              // Reset stats
              setStats({ hits: 0, misses: 0, extras: 0 });
              hitNoteIndicesRef.current.clear();
              lastCheckedNoteIndexRef.current = -1;
              lastWaitNoteIndexRef.current = -1;
              waitingForNotesRef.current.clear();
              waitingNoteIndicesRef.current.clear();
              playedWhileWaitingRef.current.clear();
              setIsWaiting(false);
            }}
            style={{ padding: '8px 16px', backgroundColor: '#FF5722', color: '#fff', border: 'none', borderRadius: 4, cursor: 'pointer' }}
          >
            Reset Stats
          </button>
        </div>
      </div>

      {/* Practice Display */}
      <div style={{ flex: 1, minHeight: 300 }}>
        <PracticeFrameDisplay
          notes={notes}
          frames={frames}
          audioBlobUrl={audioUrl}
          audioStartTime={TEST_SEGMENT.startTime}
          width={width}
          height={Math.max(300, window.innerHeight - 350)}
          onTimeUpdate={handleTimeUpdate}
          onPlayStateChange={handlePlayStateChange}
          micEnabled={false}
          onMicToggle={() => {}}
          lastDetectedNote={null}
          comparisonStats={null}
          // MIDI props - just for display, keyboard makes its own sound
          midiPressedKeys={midiPressedKeys}
          midiStats={stats}
          // Wait mode props
          waitMode={waitMode}
          onWaitModeChange={setWaitMode}
          isWaiting={isWaiting}
          waitingForNotes={waitingForNotesRef.current}
          playedNotes={playedWhileWaitingRef.current}
          pauseRef={pausePlaybackRef}
          resumeRef={resumePlaybackRef}
        />
      </div>

      {/* Keyboard - Green = expected chord, Blue = MIDI pressed */}
      <div style={{ flexShrink: 0, marginTop: 10 }}>
        <VisualKeyboard
          noteRange={noteRange}
          pressedKeys={midiPressedKeys}
          currentCorrectNotes={expectedKeys}
          currentCorrectNote={currentNoteMidi}
          distributionWidth={12}
          config={config}
          width={width}
          height={150}
        />
      </div>
    </div>
  );
}
