// Auto-generated by analysis/analyze-songs.ts — do not edit by hand.
// Re-run: npx tsx analysis/analyze-songs.ts
import type { EdgeType } from './chordPathfinder';

export interface CyclePreset {
  loop: string;         // edge-type sequence, e.g. "fifth dom7"
  length: number;       // number of steps (= edges in the loop)
  songCount: number;    // songs in the library containing this cycle
  constraints: EdgeType[];  // Walk constraints needed to traverse it
  exampleChords: string;   // concrete chord instance, e.g. "D A D"
}

export const CYCLE_PRESETS: CyclePreset[] = [
  {
    "loop": "dom7 fifth",
    "length": 2,
    "songCount": 168,
    "constraints": [
      "fifth",
      "dom7"
    ],
    "exampleChords": "F Bb F"
  },
  {
    "loop": "diatonic diatonic",
    "length": 2,
    "songCount": 126,
    "constraints": [
      "diatonic"
    ],
    "exampleChords": "A G A"
  },
  {
    "loop": "diatonic dom7 dom7",
    "length": 3,
    "songCount": 76,
    "constraints": [
      "diatonic",
      "dom7"
    ],
    "exampleChords": "A B E A"
  },
  {
    "loop": "diatonic fifth fifth",
    "length": 3,
    "songCount": 68,
    "constraints": [
      "fifth",
      "diatonic"
    ],
    "exampleChords": "A G D A"
  },
  {
    "loop": "dom7 fifth dom7 fifth",
    "length": 4,
    "songCount": 65,
    "constraints": [
      "fifth",
      "dom7"
    ],
    "exampleChords": "A D A D A"
  },
  {
    "loop": "diatonic diatonic diatonic diatonic",
    "length": 4,
    "songCount": 47,
    "constraints": [
      "diatonic"
    ],
    "exampleChords": "Em D Em D Em"
  },
  {
    "loop": "relative relative",
    "length": 2,
    "songCount": 41,
    "constraints": [
      "relative"
    ],
    "exampleChords": "C#m E C#m"
  },
  {
    "loop": "diatonic diatonic dom7 fifth",
    "length": 4,
    "songCount": 40,
    "constraints": [
      "fifth",
      "diatonic",
      "dom7"
    ],
    "exampleChords": "G F G C G"
  },
  {
    "loop": "dom7 dom7 fifth fifth",
    "length": 4,
    "songCount": 32,
    "constraints": [
      "fifth",
      "dom7"
    ],
    "exampleChords": "A D G D A"
  },
  {
    "loop": "diatonic relative fifth",
    "length": 3,
    "songCount": 32,
    "constraints": [
      "fifth",
      "diatonic",
      "relative"
    ],
    "exampleChords": "D Em G D"
  },
  {
    "loop": "dom7 dom7 dom7 relative",
    "length": 4,
    "songCount": 28,
    "constraints": [
      "relative",
      "dom7"
    ],
    "exampleChords": "Em7 Am D7 G Em7"
  },
  {
    "loop": "borrowed dom7",
    "length": 2,
    "songCount": 27,
    "constraints": [
      "borrowed",
      "dom7"
    ],
    "exampleChords": "Dm A Dm"
  },
  {
    "loop": "borrowed borrowed",
    "length": 2,
    "songCount": 21,
    "constraints": [
      "borrowed"
    ],
    "exampleChords": "G Bb G"
  },
  {
    "loop": "diatonic diatonic fifth dom7",
    "length": 4,
    "songCount": 20,
    "constraints": [
      "fifth",
      "diatonic",
      "dom7"
    ],
    "exampleChords": "C Dm C G7 C"
  },
  {
    "loop": "diatonic dom7 relative",
    "length": 3,
    "songCount": 20,
    "constraints": [
      "diatonic",
      "relative",
      "dom7"
    ],
    "exampleChords": "Cm Bb7 Eb Cm"
  },
  {
    "loop": "diatonic fifth dom7 fifth fifth",
    "length": 5,
    "songCount": 17,
    "constraints": [
      "fifth",
      "diatonic",
      "dom7"
    ],
    "exampleChords": "B A E A E B"
  },
  {
    "loop": "diatonic diatonic diatonic dom7 dom7",
    "length": 5,
    "songCount": 17,
    "constraints": [
      "diatonic",
      "dom7"
    ],
    "exampleChords": "Bb C Bb C F Bb"
  },
  {
    "loop": "diatonic fifth fifth dom7 fifth",
    "length": 5,
    "songCount": 16,
    "constraints": [
      "fifth",
      "diatonic",
      "dom7"
    ],
    "exampleChords": "E D A E A E"
  },
  {
    "loop": "diatonic diatonic diatonic fifth fifth",
    "length": 5,
    "songCount": 14,
    "constraints": [
      "fifth",
      "diatonic"
    ],
    "exampleChords": "Em7 F Em Dm Am Em7"
  },
  {
    "loop": "dom7 fifth relative relative",
    "length": 4,
    "songCount": 14,
    "constraints": [
      "fifth",
      "relative",
      "dom7"
    ],
    "exampleChords": "C7 F C Am C7"
  },
  {
    "loop": "diatonic diatonic relative",
    "length": 3,
    "songCount": 14,
    "constraints": [
      "diatonic",
      "relative"
    ],
    "exampleChords": "F Em Dm F"
  },
  {
    "loop": "diatonic dom7 dom7 fifth dom7",
    "length": 5,
    "songCount": 13,
    "constraints": [
      "fifth",
      "diatonic",
      "dom7"
    ],
    "exampleChords": "Bb C F Bb F Bb"
  },
  {
    "loop": "diatonic diatonic diatonic fifth",
    "length": 4,
    "songCount": 13,
    "constraints": [
      "fifth",
      "diatonic"
    ],
    "exampleChords": "G Am Bm C G"
  },
  {
    "loop": "diatonic diatonic relative dom7",
    "length": 4,
    "songCount": 13,
    "constraints": [
      "diatonic",
      "relative",
      "dom7"
    ],
    "exampleChords": "C D Em G C"
  },
  {
    "loop": "borrowed dom7 borrowed dom7",
    "length": 4,
    "songCount": 13,
    "constraints": [
      "borrowed",
      "dom7"
    ],
    "exampleChords": "Dm A Dm A Dm"
  },
  {
    "loop": "diatonic dom7 dom7 dom7 fifth",
    "length": 5,
    "songCount": 12,
    "constraints": [
      "fifth",
      "diatonic",
      "dom7"
    ],
    "exampleChords": "C D7 G C Fmaj7 C"
  },
  {
    "loop": "borrowed diatonic diatonic",
    "length": 3,
    "songCount": 12,
    "constraints": [
      "diatonic",
      "borrowed"
    ],
    "exampleChords": "D Bb C D"
  },
  {
    "loop": "diatonic dom7 fifth dom7 dom7",
    "length": 5,
    "songCount": 11,
    "constraints": [
      "fifth",
      "diatonic",
      "dom7"
    ],
    "exampleChords": "G A D A D G"
  },
  {
    "loop": "diatonic dom7 diatonic fifth",
    "length": 4,
    "songCount": 11,
    "constraints": [
      "fifth",
      "diatonic",
      "dom7"
    ],
    "exampleChords": "D E A G D"
  },
  {
    "loop": "borrowed fifth diatonic",
    "length": 3,
    "songCount": 11,
    "constraints": [
      "fifth",
      "diatonic",
      "borrowed"
    ],
    "exampleChords": "C Eb Bb C"
  },
  {
    "loop": "diatonic relative dom7",
    "length": 3,
    "songCount": 10,
    "constraints": [
      "diatonic",
      "relative",
      "dom7"
    ],
    "exampleChords": "C Bb Gm7 C"
  },
  {
    "loop": "borrowed dom7 dom7 dom7",
    "length": 4,
    "songCount": 9,
    "constraints": [
      "borrowed",
      "dom7"
    ],
    "exampleChords": "A F# B E A"
  },
  {
    "loop": "diatonic dom7 diatonic relative",
    "length": 4,
    "songCount": 9,
    "constraints": [
      "diatonic",
      "relative",
      "dom7"
    ],
    "exampleChords": "F G C Dm7 F"
  },
  {
    "loop": "diatonic diatonic fifth relative",
    "length": 4,
    "songCount": 9,
    "constraints": [
      "fifth",
      "diatonic",
      "relative"
    ],
    "exampleChords": "G#m F# E B G#m"
  },
  {
    "loop": "diatonic diatonic diatonic diatonic relative",
    "length": 5,
    "songCount": 8,
    "constraints": [
      "diatonic",
      "relative"
    ],
    "exampleChords": "F Em Dm C Dm F"
  },
  {
    "loop": "diatonic relative fifth dom7 fifth",
    "length": 5,
    "songCount": 8,
    "constraints": [
      "fifth",
      "diatonic",
      "relative",
      "dom7"
    ],
    "exampleChords": "Db Ebm7 Gb Db Gb Db"
  },
  {
    "loop": "relative relative relative relative",
    "length": 4,
    "songCount": 7,
    "constraints": [
      "relative"
    ],
    "exampleChords": "C#m E C#m E C#m"
  },
  {
    "loop": "borrowed fifth fifth fifth",
    "length": 4,
    "songCount": 7,
    "constraints": [
      "fifth",
      "borrowed"
    ],
    "exampleChords": "F Ab Eb Bb F"
  },
  {
    "loop": "diatonic diatonic diatonic dom7",
    "length": 4,
    "songCount": 7,
    "constraints": [
      "diatonic",
      "dom7"
    ],
    "exampleChords": "F Em Dm C F"
  },
  {
    "loop": "borrowed dom7 parallel",
    "length": 3,
    "songCount": 7,
    "constraints": [
      "borrowed",
      "parallel",
      "dom7"
    ],
    "exampleChords": "Bbm F Bb Bbm"
  }
];